#############################################################################
# Makefile for building: HockeySim_GUI.app/Contents/MacOS/HockeySim_GUI
# Generated by qmake (3.1) (Qt 6.11.0)
# Project:  HockeySim_GUI.pro
# Template: app
# Command: /Users/drewb/Desktop/Software_Development/6.11.0/macos/bin/qmake -o Makefile HockeySim_GUI.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=13 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=13 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../6.11.0/macos/lib/QtWidgets.framework/Headers -I../6.11.0/macos/lib/QtGui.framework/Headers -I../6.11.0/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I../6.11.0/macos/mkspecs/macx-clang -F/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib
QMAKE         = /Users/drewb/Desktop/Software_Development/6.11.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/drewb/Desktop/Software_Development/6.11.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/drewb/Desktop/Software_Development/6.11.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = HockeySim_GUI1.0.0
DISTDIR = /Users/drewb/Desktop/Software_Development/Final_Project/.tmp/HockeySim_GUI1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../6.11.0/macos/mkspecs/features/spec_pre.prf \
		../6.11.0/macos/mkspecs/features/device_config.prf \
		../6.11.0/macos/mkspecs/common/unix.conf \
		../6.11.0/macos/mkspecs/common/mac.conf \
		../6.11.0/macos/mkspecs/common/macx.conf \
		../6.11.0/macos/mkspecs/common/sanitize.conf \
		../6.11.0/macos/mkspecs/common/gcc-base.conf \
		../6.11.0/macos/mkspecs/common/gcc-base-mac.conf \
		../6.11.0/macos/mkspecs/common/clang.conf \
		../6.11.0/macos/mkspecs/common/clang-mac.conf \
		../6.11.0/macos/mkspecs/qconfig.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_core.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_help.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekit.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssynchronizer.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_network.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickshapes.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_tasktree.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_tasktree_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../6.11.0/macos/mkspecs/features/qt_functions.prf \
		../6.11.0/macos/mkspecs/features/qt_config.prf \
		../6.11.0/macos/mkspecs/macx-clang/qmake.conf \
		../6.11.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../6.11.0/macos/mkspecs/features/exclusive_builds.prf \
		../6.11.0/macos/mkspecs/features/mac/sdk.prf \
		../6.11.0/macos/mkspecs/features/toolchain.prf \
		../6.11.0/macos/mkspecs/features/mac/toolchain.prf \
		../6.11.0/macos/mkspecs/features/default_pre.prf \
		../6.11.0/macos/mkspecs/features/mac/default_pre.prf \
		../6.11.0/macos/mkspecs/features/resolve_config.prf \
		../6.11.0/macos/mkspecs/features/default_post.prf \
		../6.11.0/macos/mkspecs/features/mac/default_post.prf \
		../6.11.0/macos/mkspecs/features/mac/objective_c.prf \
		../6.11.0/macos/mkspecs/features/qml_debug.prf \
		../6.11.0/macos/mkspecs/features/mac/mac.prf \
		../6.11.0/macos/mkspecs/features/warn_on.prf \
		../6.11.0/macos/mkspecs/features/permissions.prf \
		../6.11.0/macos/mkspecs/features/qt.prf \
		../6.11.0/macos/mkspecs/features/resources_functions.prf \
		../6.11.0/macos/mkspecs/features/resources.prf \
		../6.11.0/macos/mkspecs/features/moc.prf \
		../6.11.0/macos/mkspecs/features/unix/opengl.prf \
		../6.11.0/macos/mkspecs/features/uic.prf \
		../6.11.0/macos/mkspecs/features/unix/thread.prf \
		../6.11.0/macos/mkspecs/features/qmake_use.prf \
		../6.11.0/macos/mkspecs/features/file_copies.prf \
		../6.11.0/macos/mkspecs/features/mac/rez.prf \
		../6.11.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../6.11.0/macos/mkspecs/features/testcase_targets.prf \
		../6.11.0/macos/mkspecs/features/exceptions.prf \
		../6.11.0/macos/mkspecs/features/yacc.prf \
		../6.11.0/macos/mkspecs/features/lex.prf \
		HockeySim_GUI.pro GameLogic.h \
		Player.h \
		mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = HockeySim_GUI
DESTDIR       = 
TARGET        = HockeySim_GUI.app/Contents/MacOS/HockeySim_GUI

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.2
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/drewb/Desktop/Software_Development/Final_Project/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/drewb/Desktop/Software_Development/Final_Project/HockeySim_GUI.pro


include /Users/drewb/Desktop/Software_Development/6.11.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

HockeySim_GUI.app/Contents/MacOS/HockeySim_GUI: ui_mainwindow.h $(OBJECTS)  
	@test -d HockeySim_GUI.app/Contents/MacOS/ || mkdir -p HockeySim_GUI.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HockeySim_GUI.pro ../6.11.0/macos/mkspecs/macx-clang/qmake.conf ../6.11.0/macos/mkspecs/features/spec_pre.prf \
		../6.11.0/macos/mkspecs/features/device_config.prf \
		../6.11.0/macos/mkspecs/common/unix.conf \
		../6.11.0/macos/mkspecs/common/mac.conf \
		../6.11.0/macos/mkspecs/common/macx.conf \
		../6.11.0/macos/mkspecs/common/sanitize.conf \
		../6.11.0/macos/mkspecs/common/gcc-base.conf \
		../6.11.0/macos/mkspecs/common/gcc-base-mac.conf \
		../6.11.0/macos/mkspecs/common/clang.conf \
		../6.11.0/macos/mkspecs/common/clang-mac.conf \
		../6.11.0/macos/mkspecs/qconfig.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../6.11.0/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_core.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_help.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekit.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssynchronizer.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_network.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickshapes.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_tasktree.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_tasktree_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../6.11.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../6.11.0/macos/mkspecs/features/qt_functions.prf \
		../6.11.0/macos/mkspecs/features/qt_config.prf \
		../6.11.0/macos/mkspecs/macx-clang/qmake.conf \
		../6.11.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../6.11.0/macos/mkspecs/features/exclusive_builds.prf \
		../6.11.0/macos/mkspecs/features/mac/sdk.prf \
		../6.11.0/macos/mkspecs/features/toolchain.prf \
		../6.11.0/macos/mkspecs/features/mac/toolchain.prf \
		../6.11.0/macos/mkspecs/features/default_pre.prf \
		../6.11.0/macos/mkspecs/features/mac/default_pre.prf \
		../6.11.0/macos/mkspecs/features/resolve_config.prf \
		../6.11.0/macos/mkspecs/features/default_post.prf \
		../6.11.0/macos/mkspecs/features/mac/default_post.prf \
		../6.11.0/macos/mkspecs/features/mac/objective_c.prf \
		../6.11.0/macos/mkspecs/features/qml_debug.prf \
		../6.11.0/macos/mkspecs/features/mac/mac.prf \
		../6.11.0/macos/mkspecs/features/warn_on.prf \
		../6.11.0/macos/mkspecs/features/permissions.prf \
		../6.11.0/macos/mkspecs/features/qt.prf \
		../6.11.0/macos/mkspecs/features/resources_functions.prf \
		../6.11.0/macos/mkspecs/features/resources.prf \
		../6.11.0/macos/mkspecs/features/moc.prf \
		../6.11.0/macos/mkspecs/features/unix/opengl.prf \
		../6.11.0/macos/mkspecs/features/uic.prf \
		../6.11.0/macos/mkspecs/features/unix/thread.prf \
		../6.11.0/macos/mkspecs/features/qmake_use.prf \
		../6.11.0/macos/mkspecs/features/file_copies.prf \
		../6.11.0/macos/mkspecs/features/mac/rez.prf \
		../6.11.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../6.11.0/macos/mkspecs/features/testcase_targets.prf \
		../6.11.0/macos/mkspecs/features/exceptions.prf \
		../6.11.0/macos/mkspecs/features/yacc.prf \
		../6.11.0/macos/mkspecs/features/lex.prf \
		HockeySim_GUI.pro \
		../6.11.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../6.11.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../6.11.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile HockeySim_GUI.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../6.11.0/macos/mkspecs/features/spec_pre.prf:
../6.11.0/macos/mkspecs/features/device_config.prf:
../6.11.0/macos/mkspecs/common/unix.conf:
../6.11.0/macos/mkspecs/common/mac.conf:
../6.11.0/macos/mkspecs/common/macx.conf:
../6.11.0/macos/mkspecs/common/sanitize.conf:
../6.11.0/macos/mkspecs/common/gcc-base.conf:
../6.11.0/macos/mkspecs/common/gcc-base-mac.conf:
../6.11.0/macos/mkspecs/common/clang.conf:
../6.11.0/macos/mkspecs/common/clang-mac.conf:
../6.11.0/macos/mkspecs/qconfig.pri:
../6.11.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../6.11.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../6.11.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../6.11.0/macos/mkspecs/modules/qt_ext_openxr_loader.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_charts.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_charts_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_core.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_designer.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_gui.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_help.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsplatform.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekit.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekit_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekitimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labssynchronizer.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labssynchronizer_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_multimedia.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_network.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qml.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3d.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dxr.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickeffects.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickshapes.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_shadertools.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_sql.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_svg.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_tasktree.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_tasktree_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_xml.pri:
../6.11.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../6.11.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../6.11.0/macos/mkspecs/features/qt_functions.prf:
../6.11.0/macos/mkspecs/features/qt_config.prf:
../6.11.0/macos/mkspecs/macx-clang/qmake.conf:
../6.11.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../6.11.0/macos/mkspecs/features/exclusive_builds.prf:
../6.11.0/macos/mkspecs/features/mac/sdk.prf:
../6.11.0/macos/mkspecs/features/toolchain.prf:
../6.11.0/macos/mkspecs/features/mac/toolchain.prf:
../6.11.0/macos/mkspecs/features/default_pre.prf:
../6.11.0/macos/mkspecs/features/mac/default_pre.prf:
../6.11.0/macos/mkspecs/features/resolve_config.prf:
../6.11.0/macos/mkspecs/features/default_post.prf:
../6.11.0/macos/mkspecs/features/mac/default_post.prf:
../6.11.0/macos/mkspecs/features/mac/objective_c.prf:
../6.11.0/macos/mkspecs/features/qml_debug.prf:
../6.11.0/macos/mkspecs/features/mac/mac.prf:
../6.11.0/macos/mkspecs/features/warn_on.prf:
../6.11.0/macos/mkspecs/features/permissions.prf:
../6.11.0/macos/mkspecs/features/qt.prf:
../6.11.0/macos/mkspecs/features/resources_functions.prf:
../6.11.0/macos/mkspecs/features/resources.prf:
../6.11.0/macos/mkspecs/features/moc.prf:
../6.11.0/macos/mkspecs/features/unix/opengl.prf:
../6.11.0/macos/mkspecs/features/uic.prf:
../6.11.0/macos/mkspecs/features/unix/thread.prf:
../6.11.0/macos/mkspecs/features/qmake_use.prf:
../6.11.0/macos/mkspecs/features/file_copies.prf:
../6.11.0/macos/mkspecs/features/mac/rez.prf:
../6.11.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../6.11.0/macos/mkspecs/features/testcase_targets.prf:
../6.11.0/macos/mkspecs/features/exceptions.prf:
../6.11.0/macos/mkspecs/features/yacc.prf:
../6.11.0/macos/mkspecs/features/lex.prf:
HockeySim_GUI.pro:
../6.11.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../6.11.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../6.11.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile HockeySim_GUI.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

HockeySim_GUI.app/Contents/PkgInfo: 
	@test -d HockeySim_GUI.app/Contents || mkdir -p HockeySim_GUI.app/Contents
	@$(DEL_FILE) HockeySim_GUI.app/Contents/PkgInfo
	@echo "APPL????" > HockeySim_GUI.app/Contents/PkgInfo
HockeySim_GUI.app/Contents/Info.plist: 
	@test -d HockeySim_GUI.app/Contents || mkdir -p HockeySim_GUI.app/Contents
	@$(DEL_FILE) HockeySim_GUI.app/Contents/Info.plist
	@set -o pipefail && plutil -convert xml1 -o - ../6.11.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.HockeySim-GUI,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.HockeySim-GUI,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,HockeySim_GUI,g" -e "s,@LIBRARY@,HockeySim_GUI,g" -e "s,\$${EXECUTABLE_NAME},HockeySim_GUI,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >HockeySim_GUI.app/Contents/Info.plist

all: Makefile \
		HockeySim_GUI.app/Contents/PkgInfo \
		HockeySim_GUI.app/Contents/Info.plist HockeySim_GUI.app/Contents/MacOS/HockeySim_GUI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents GameLogic.h Player.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r HockeySim_GUI.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../6.11.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		Player.h \
		../6.11.0/macos/libexec/moc
	/Users/drewb/Desktop/Software_Development/6.11.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=16 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/drewb/Desktop/Software_Development/6.11.0/macos/mkspecs/macx-clang -I/Users/drewb/Desktop/Software_Development/Final_Project -I/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib/QtWidgets.framework/Headers -I/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib/QtGui.framework/Headers -I/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/16/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/drewb/Desktop/Software_Development/6.11.0/macos/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../6.11.0/macos/libexec/uic
	/Users/drewb/Desktop/Software_Development/6.11.0/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../6.11.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		Player.h \
		../6.11.0/macos/lib/QtWidgets.framework/Headers/QApplication
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../6.11.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		Player.h \
		ui_mainwindow.h \
		GameLogic.h \
		../6.11.0/macos/lib/QtWidgets.framework/Headers/QInputDialog \
		../6.11.0/macos/lib/QtCore.framework/Headers/QTimer
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/HockeySim_GUI/bin || mkdir -p $(INSTALL_ROOT)/opt/HockeySim_GUI/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/HockeySim_GUI/bin/HockeySim_GUI.app
	
	$(QINSTALL) HockeySim_GUI.app $(INSTALL_ROOT)/opt/HockeySim_GUI/bin/HockeySim_GUI.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/HockeySim_GUI/bin/HockeySim_GUI.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/HockeySim_GUI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

